<a href="https://colab.research.google.com/github/vishal2002begani/machine_learning/blob/main/Numpy_fundamentals.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

### What is numpy?

NumPy is the fundamental package for scientific computing in Python. It is a Python library that provides a multidimensional array object, various derived objects (such as masked arrays and matrices), and an assortment of routines for fast operations on arrays, including mathematical, logical, shape manipulation, sorting, selecting, I/O, discrete Fourier transforms, basic linear algebra, basic statistical operations, random simulation and much more.


At the core of the NumPy package, is the ndarray object. This encapsulates n-dimensional arrays of homogeneous data types

### Numpy Arrays Vs Python Sequences

- NumPy arrays have a fixed size at creation, unlike Python lists (which can grow dynamically). Changing the size of an ndarray will create a new array and delete the original.

- The elements in a NumPy array are all required to be of the same data type, and thus will be the same size in memory.

- NumPy arrays facilitate advanced mathematical and other types of operations on large numbers of data. Typically, such operations are executed more efficiently and with less code than is possible using Python’s built-in sequences.

- A growing plethora of scientific and mathematical Python-based packages are using NumPy arrays; though these typically support Python-sequence input, they convert such input to NumPy arrays prior to processing, and they often output NumPy arrays.

### Creating Numpy Arrays

In [56]:
# np.array
import numpy as np
a = np.array([1,2,3])
print(a)

# 2D and 3D
b = np.array([[1,2,3],[4,5,6]])
print(b)

c = np.array([[[1,2],[3,4]],[[5,6],[7,8]]])
print(c)

[1 2 3]
[[1 2 3]
 [4 5 6]]
[[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]]


In [57]:
# dtype
np.array([1,2,3],dtype=np.int32) # dtype float np.int32 float and other data types bhi de sakte hai

array([1, 2, 3], dtype=int32)

In [58]:
# np.arange
np.arange(1,13,2) # by default step size 1 hota hai and last vala included nhi hota

array([ 1,  3,  5,  7,  9, 11])

In [59]:
# with reshape
np.arange(16).reshape(2,2,2,2)

array([[[[ 0,  1],
         [ 2,  3]],

        [[ 4,  5],
         [ 6,  7]]],


       [[[ 8,  9],
         [10, 11]],

        [[12, 13],
         [14, 15]]]])

In [60]:
# np.ones and np.zeros
np.ones((3,4),dtype=np.int32)# input mai tuple lega and default data type is float

array([[1, 1, 1, 1],
       [1, 1, 1, 1],
       [1, 1, 1, 1]], dtype=int32)

In [61]:
np.zeros((3,4))# input mai tuple lega and default data type is float

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [62]:
# np.random
np.random.random((3,4))

array([[0.87326271, 0.96347712, 0.14971206, 0.99350415],
       [0.02614261, 0.11255049, 0.53614295, 0.52119428],
       [0.90147911, 0.52429972, 0.1663034 , 0.67758294]])

In [63]:
# np.linspace
np.linspace(-10,10,10,dtype=int) # first and last are included by default datatype is float

array([-10,  -8,  -6,  -4,  -2,   1,   3,   5,   7,  10])

In [64]:
# np.identity
np.identity(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

### Array Attributes

In [65]:
a1 = np.arange(10,dtype=np.int32)
a2 = np.arange(12,dtype=float).reshape(3,4)
a3 = np.arange(8).reshape(2,2,2)

In [66]:
# ndim
a3.ndim # dimension of data

3

In [67]:
# shape
print(a3.shape)
a3

(2, 2, 2)


array([[[0, 1],
        [2, 3]],

       [[4, 5],
        [6, 7]]])

In [68]:
# size
print(a2.size) # no of elements
a2

12


array([[ 0.,  1.,  2.,  3.],
       [ 4.,  5.,  6.,  7.],
       [ 8.,  9., 10., 11.]])

In [69]:
# itemsize
a3.itemsize # each item memory mai kitna space le raha hai

8

In [70]:
# dtype datatype of complete array
a=np.array([1,'2',1.2]);
print(a.dtype)
print(a1.dtype)
print(a2.dtype)
print(a3.dtype)

<U32
int32
float64
int64


### Changing Datatype

In [71]:
# astype typecasting
a3.astype(np.int32)

array([[[0, 1],
        [2, 3]],

       [[4, 5],
        [6, 7]]], dtype=int32)

### Array Operations

In [72]:
a1 = np.arange(12).reshape(3,4)
a2 = np.arange(12,24).reshape(3,4)
a2

array([[12, 13, 14, 15],
       [16, 17, 18, 19],
       [20, 21, 22, 23]])

In [73]:
# scalar operations arithmetic
a1 ** 2 # item wise operation ho jaayega

array([[  0,   1,   4,   9],
       [ 16,  25,  36,  49],
       [ 64,  81, 100, 121]])

In [74]:
# relational
a2 == 15

array([[False, False, False,  True],
       [False, False, False, False],
       [False, False, False, False]])

In [75]:
# vector operations arithmetic
a1 ** a2 #same shape so item wise operation ho jaayega

array([[                   0,                    1,                16384,
                    14348907],
       [          4294967296,         762939453125,      101559956668416,
           11398895185373143],
       [ 1152921504606846976, -1261475310744950487,  1864712049423024128,
         6839173302027254275]])

### Array Functions

In [76]:
a1 = np.random.random((3,3))
a1 = np.round(a1*10)
a1

array([[9., 9., 3.],
       [6., 4., 5.],
       [6., 8., 2.]])

In [77]:
# max/min/sum/prod
print(np.max(a1))
print(np.min(a1))
print(np.sum(a1))
print(np.prod(a1))
# 0 -> col and 1 -> row
print(np.max(a1,axis=0))
print(np.min(a1,axis=1))
print(np.sum(a1,axis=0))
print(np.prod(a1,axis=0))

9.0
2.0
52.0
2799360.0
[9. 9. 5.]
[3. 4. 2.]
[21. 21. 10.]
[324. 288.  30.]


In [78]:
# mean/median/std/var
print(np.mean(a1,axis=1))# if axis is not given then it will calculate for whole tensor
print(np.median(a1))
print(np.std(a1))
print(np.var(a1,axis=1))

[7.         5.         5.33333333]
6.0
2.3934065809486684
[8.         0.66666667 6.22222222]


In [79]:
# trigonomoetric functions
np.sin(a1)

array([[ 0.41211849,  0.41211849,  0.14112001],
       [-0.2794155 , -0.7568025 , -0.95892427],
       [-0.2794155 ,  0.98935825,  0.90929743]])

In [80]:
# dot product
a2 = np.arange(12).reshape(3,4)
a3 = np.arange(12,24).reshape(4,3)
np.dot(a2,a3)

array([[114, 120, 126],
       [378, 400, 422],
       [642, 680, 718]])

In [81]:
# log and exponents
np.exp(a1)
np.log(a1)

array([[2.19722458, 2.19722458, 1.09861229],
       [1.79175947, 1.38629436, 1.60943791],
       [1.79175947, 2.07944154, 0.69314718]])

In [82]:
# round/floor/ceil
np.ceil(np.random.random((2,3))*100)

array([[81., 92., 32.],
       [68., 95.,  1.]])

### Indexing and Slicing

In [83]:
a1 = np.arange(10)
a2 = np.arange(12).reshape(3,4)
a3 = np.arange(8).reshape(2,2,2)

In [84]:
print(a1)
print(a1[2:5])
print(a1[2:5:2]) # step size 2 start:end:step_size

[0 1 2 3 4 5 6 7 8 9]
[2 3 4]
[2 4]


In [85]:
a2
print(a2[1,0])
print(a2[:,2])
print(a2[2,:]) # if nothing is written after colon means select all
print(a2[1:2,1:3])
print(a2[0:,0:5:2]) # here 2 is step size

4
[ 2  6 10]
[ 8  9 10 11]
[[5 6]]
[[ 0  2]
 [ 4  6]
 [ 8 10]]


In [86]:
a2[0:2,1::2]
a2[::2,1::2]
a2[1,::3]
a2[0,:]
a2[:,2]
a2[1:,1:3]

array([[ 5,  6],
       [ 9, 10]])

In [87]:
a3 = np.arange(27).reshape(3,3,3)
a3
a3[1,0,1]
a3[1,1,0]

12

In [88]:
a3[::2,0,::2]
a3[2,1:,1:]
a3[0,1,:]
a3[0::2,0,0::2]

array([[ 0,  2],
       [18, 20]])

### Iterating

In [89]:
a1
for i in a1:
  print(i)

0
1
2
3
4
5
6
7
8
9


In [90]:
a2

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [91]:
for i in a2:
  print(i)

[0 1 2 3]
[4 5 6 7]
[ 8  9 10 11]


In [92]:
a3

array([[[ 0,  1,  2],
        [ 3,  4,  5],
        [ 6,  7,  8]],

       [[ 9, 10, 11],
        [12, 13, 14],
        [15, 16, 17]],

       [[18, 19, 20],
        [21, 22, 23],
        [24, 25, 26]]])

In [93]:
for i in a3:
  print(i)

[[0 1 2]
 [3 4 5]
 [6 7 8]]
[[ 9 10 11]
 [12 13 14]
 [15 16 17]]
[[18 19 20]
 [21 22 23]
 [24 25 26]]


In [94]:
for i in np.nditer(a3): # iterate to all elements
  print(i)

0
1
2
3
4
5
6
7
8
9
10
11
12
13
14
15
16
17
18
19
20
21
22
23
24
25
26


### Reshaping

In [95]:
# reshape

In [96]:
# Transpose
np.transpose(a2) # both are same
a2.T

array([[ 0,  4,  8],
       [ 1,  5,  9],
       [ 2,  6, 10],
       [ 3,  7, 11]])

In [97]:
# ravel
a3.ravel() # convert into 1d array

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26])

### Stacking

In [98]:
# horizontal stacking
a4 = np.arange(12).reshape(3,4)
a5 = np.arange(12,24).reshape(3,4)
a5

array([[12, 13, 14, 15],
       [16, 17, 18, 19],
       [20, 21, 22, 23]])

In [99]:
np.hstack((a4,a5))

array([[ 0,  1,  2,  3, 12, 13, 14, 15],
       [ 4,  5,  6,  7, 16, 17, 18, 19],
       [ 8,  9, 10, 11, 20, 21, 22, 23]])

In [100]:
# Vertical stacking
np.vstack((a4,a5))

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15],
       [16, 17, 18, 19],
       [20, 21, 22, 23]])

### Splitting

In [101]:
# horizontal splitting
a4

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [102]:
np.hsplit(a4,2)

[array([[0, 1],
        [4, 5],
        [8, 9]]),
 array([[ 2,  3],
        [ 6,  7],
        [10, 11]])]

In [103]:
# vertical splitting

In [104]:
a5

array([[12, 13, 14, 15],
       [16, 17, 18, 19],
       [20, 21, 22, 23]])

In [105]:
np.vsplit(a5,2) # 3 rows so not possible to dive equally

ValueError: array split does not result in an equal division