<a href="https://colab.research.google.com/github/vishal2002begani/machine_learning/blob/main/Numpy_functions_with_documentation.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

### np.sort

Return a sorted copy of an array.

https://numpy.org/doc/stable/reference/generated/numpy.sort.html

In [65]:
# code
import numpy as np
a = np.random.randint(1,100,15)
a

array([18, 69,  1, 84, 66, 91, 11, 29, 39, 64, 44, 57, 79, 82, 80])

In [66]:
b = np.random.randint(1,100,24).reshape(6,4)
b

array([[37, 39, 54, 66],
       [46, 37, 55,  8],
       [ 7, 88, 98, 28],
       [ 2, 68, 64, 66],
       [99, 74, 16, 69],
       [83, 98, 43, 27]])

In [67]:
np.sort(a)

array([ 1, 11, 18, 29, 39, 44, 57, 64, 66, 69, 79, 80, 82, 84, 91])

In [68]:
np.sort(a)[::-1] #-1 means reverse indexing

array([91, 84, 82, 80, 79, 69, 66, 64, 57, 44, 39, 29, 18, 11,  1])

In [69]:
np.sort(b,axis=0)[::-1]

array([[99, 98, 98, 69],
       [83, 88, 64, 66],
       [46, 74, 55, 66],
       [37, 68, 54, 28],
       [ 7, 39, 43, 27],
       [ 2, 37, 16,  8]])

### np.append

The numpy.append() appends values along the mentioned axis at the end of the array

https://numpy.org/doc/stable/reference/generated/numpy.append.html

In [70]:
# code
np.append(a,200)

array([ 18,  69,   1,  84,  66,  91,  11,  29,  39,  64,  44,  57,  79,
        82,  80, 200])

In [71]:
b

array([[37, 39, 54, 66],
       [46, 37, 55,  8],
       [ 7, 88, 98, 28],
       [ 2, 68, 64, 66],
       [99, 74, 16, 69],
       [83, 98, 43, 27]])

In [72]:
np.append(b,np.random.randint(1,10,b.shape[0]).reshape(b.shape[0],1),axis=1) # added a new column

array([[37, 39, 54, 66,  9],
       [46, 37, 55,  8,  1],
       [ 7, 88, 98, 28,  8],
       [ 2, 68, 64, 66,  7],
       [99, 74, 16, 69,  4],
       [83, 98, 43, 27,  6]])

In [73]:
np.append(b,np.random.randint(1,10,b.shape[1]).reshape(1,b.shape[1]),axis=0) # added a new row

array([[37, 39, 54, 66],
       [46, 37, 55,  8],
       [ 7, 88, 98, 28],
       [ 2, 68, 64, 66],
       [99, 74, 16, 69],
       [83, 98, 43, 27],
       [ 8,  9,  9,  1]])

### np.concatenate

numpy.concatenate() function concatenate a sequence of arrays along an existing axis.

https://numpy.org/doc/stable/reference/generated/numpy.concatenate.html

In [74]:
# code
c = np.arange(6).reshape(2,3)
d = np.arange(6,12).reshape(2,3)

print(c)
print(d)

[[0 1 2]
 [3 4 5]]
[[ 6  7  8]
 [ 9 10 11]]


In [75]:
np.concatenate((c,d),axis=0) # just like hstack and vstack

array([[ 0,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8],
       [ 9, 10, 11]])

In [76]:
np.concatenate((c,d,c),axis=1)

array([[ 0,  1,  2,  6,  7,  8,  0,  1,  2],
       [ 3,  4,  5,  9, 10, 11,  3,  4,  5]])

### np.unique

With the help of np.unique() method, we can get the unique values from an array given as parameter in np.unique() method.

https://numpy.org/doc/stable/reference/generated/numpy.unique.html/

In [77]:
# code
e = np.array([1,1,2,2,3,3,4,4,5,5,6,6])

In [78]:
np.unique(e)

array([1, 2, 3, 4, 5, 6])

### np.expand_dims

With the help of Numpy.expand_dims() method, we can get the expanded dimensions of an array

https://numpy.org/doc/stable/reference/generated/numpy.expand_dims.html

In [79]:
# code
a.shape

(15,)

In [80]:
np.expand_dims(a,axis=0).shape

(1, 15)

In [81]:
np.expand_dims(a,axis=1).shape

(15, 1)

In [82]:
np.expand_dims(a,axis=1)

array([[18],
       [69],
       [ 1],
       [84],
       [66],
       [91],
       [11],
       [29],
       [39],
       [64],
       [44],
       [57],
       [79],
       [82],
       [80]])

### np.where

The numpy.where() function returns the indices of elements in an input array where the given condition is satisfied.

https://numpy.org/doc/stable/reference/generated/numpy.where.html

In [83]:
a

array([18, 69,  1, 84, 66, 91, 11, 29, 39, 64, 44, 57, 79, 82, 80])

In [84]:
# find all indices with value greater than 50
np.where(a>50)

(array([ 1,  3,  4,  5,  9, 11, 12, 13, 14]),)

In [85]:
# replace all values > 50 with 0
# np.where(condition,true ,false)
np.where(a>50,0,a)

array([18,  0,  1,  0,  0,  0, 11, 29, 39,  0, 44,  0,  0,  0,  0])

In [86]:
np.where(a%2 == 0,0,a)

array([ 0, 69,  1,  0,  0, 91, 11, 29, 39,  0,  0, 57, 79,  0,  0])

### np.argmax

The numpy.argmax() function returns indices of the max element of the array in a particular axis.

https://numpy.org/doc/stable/reference/generated/numpy.argmax.html

In [87]:
# code
a

array([18, 69,  1, 84, 66, 91, 11, 29, 39, 64, 44, 57, 79, 82, 80])

In [88]:
np.argmax(a)

5

In [89]:
b

array([[37, 39, 54, 66],
       [46, 37, 55,  8],
       [ 7, 88, 98, 28],
       [ 2, 68, 64, 66],
       [99, 74, 16, 69],
       [83, 98, 43, 27]])

In [90]:
np.argmax(b,axis=0)

array([4, 5, 2, 4])

In [91]:
np.argmax(b,axis=1)

array([3, 2, 2, 1, 0, 1])

In [92]:
# np.argmin
np.argmin(a)

2

### np.cumsum

numpy.cumsum() function is used when we want to compute the cumulative sum of array elements over a given axis.

https://numpy.org/doc/stable/reference/generated/numpy.cumsum.html

In [93]:
a

array([18, 69,  1, 84, 66, 91, 11, 29, 39, 64, 44, 57, 79, 82, 80])

In [94]:
np.cumsum(a)

array([ 18,  87,  88, 172, 238, 329, 340, 369, 408, 472, 516, 573, 652,
       734, 814])

In [95]:
b

array([[37, 39, 54, 66],
       [46, 37, 55,  8],
       [ 7, 88, 98, 28],
       [ 2, 68, 64, 66],
       [99, 74, 16, 69],
       [83, 98, 43, 27]])

In [96]:
np.cumsum(b,axis=1)

array([[ 37,  76, 130, 196],
       [ 46,  83, 138, 146],
       [  7,  95, 193, 221],
       [  2,  70, 134, 200],
       [ 99, 173, 189, 258],
       [ 83, 181, 224, 251]])

In [97]:
np.cumsum(b)

array([  37,   76,  130,  196,  242,  279,  334,  342,  349,  437,  535,
        563,  565,  633,  697,  763,  862,  936,  952, 1021, 1104, 1202,
       1245, 1272])

In [98]:
# np.cumprod
np.cumprod(a)

array([                  18,                 1242,                 1242,
                     104328,              6885648,            626593968,
                 6892533648,         199883475792,        7795455555888,
            498909155576832,    21952002845380608,  1251264162186694656,
        6616148444201119744,  7568594286914822144, -3255011479229431808])

In [99]:
a

array([18, 69,  1, 84, 66, 91, 11, 29, 39, 64, 44, 57, 79, 82, 80])

### np.percentile

numpy.percentile()function used to compute the nth percentile of the given data (array elements) along the specified axis.

https://numpy.org/doc/stable/reference/generated/numpy.percentile.html

In [100]:
a

array([18, 69,  1, 84, 66, 91, 11, 29, 39, 64, 44, 57, 79, 82, 80])

In [101]:
np.percentile(a,50)

64.0

In [102]:
np.median(a)

64.0

### np.histogram

Numpy has a built-in numpy.histogram() function which represents the frequency of data distribution in the graphical form.

https://numpy.org/doc/stable/reference/generated/numpy.histogram.html

In [103]:
# code
a

array([18, 69,  1, 84, 66, 91, 11, 29, 39, 64, 44, 57, 79, 82, 80])

In [104]:
np.histogram(a,bins=[0,20,40,60,80,100]) # inside bins we will give our range of partition

(array([3, 2, 2, 4, 4]), array([  0,  20,  40,  60,  80, 100]))

### np.corrcoef

Return Pearson product-moment correlation coefficients.

https://numpy.org/doc/stable/reference/generated/numpy.corrcoef.html

In [105]:
salary = np.array([20000,40000,25000,35000,60000])
experience = np.array([1,3,2,4,2])

np.corrcoef(salary,experience)

array([[1.        , 0.25344572],
       [0.25344572, 1.        ]])

### np.isin

With the help of numpy.isin() method, we can see that one array having values are checked in a different numpy array having different elements with different sizes.

https://numpy.org/doc/stable/reference/generated/numpy.isin.html

In [106]:
# code
a


array([18, 69,  1, 84, 66, 91, 11, 29, 39, 64, 44, 57, 79, 82, 80])

In [107]:
items = [10,20,30,40,50,60,70,80,90,100]

a[np.isin(a,items)]

array([80])

### np.flip

The numpy.flip() function reverses the order of array elements along the specified axis, preserving the shape of the array.

https://numpy.org/doc/stable/reference/generated/numpy.flip.html

In [108]:
# code
print(a)
np.flip(a)

[18 69  1 84 66 91 11 29 39 64 44 57 79 82 80]


array([80, 82, 79, 57, 44, 64, 39, 29, 11, 91, 66, 84,  1, 69, 18])

In [109]:
print(b)
np.flip(b) #both fliping column and row

[[37 39 54 66]
 [46 37 55  8]
 [ 7 88 98 28]
 [ 2 68 64 66]
 [99 74 16 69]
 [83 98 43 27]]


array([[27, 43, 98, 83],
       [69, 16, 74, 99],
       [66, 64, 68,  2],
       [28, 98, 88,  7],
       [ 8, 55, 37, 46],
       [66, 54, 39, 37]])

In [110]:
np.flip(b,axis=1)

array([[66, 54, 39, 37],
       [ 8, 55, 37, 46],
       [28, 98, 88,  7],
       [66, 64, 68,  2],
       [69, 16, 74, 99],
       [27, 43, 98, 83]])

### np.put

The numpy.put() function replaces specific elements of an array with given values of p_array. Array indexed works on flattened array.

https://numpy.org/doc/stable/reference/generated/numpy.put.html

In [111]:
# code
a

array([18, 69,  1, 84, 66, 91, 11, 29, 39, 64, 44, 57, 79, 82, 80])

In [112]:
np.put(a,[0,1],[110,530]) #permanent changes in the array
# np.put(a,[index],[replace with])
print(a)

[110 530   1  84  66  91  11  29  39  64  44  57  79  82  80]


### np.delete

The numpy.delete() function returns a new array with the deletion of sub-arrays along with the mentioned axis.

https://numpy.org/doc/stable/reference/generated/numpy.delete.html

In [113]:
# code
a

array([110, 530,   1,  84,  66,  91,  11,  29,  39,  64,  44,  57,  79,
        82,  80])

In [114]:
np.delete(a,[0,2,4])

array([530,  84,  91,  11,  29,  39,  64,  44,  57,  79,  82,  80])

### Set functions

- np.union1d
- np.intersect1d
- np.setdiff1d
- np.setxor1d
- np.in1d

In [115]:
m = np.array([1,2,3,4,5])
n = np.array([3,4,5,6,7])

np.union1d(m,n)

array([1, 2, 3, 4, 5, 6, 7])

In [116]:
np.intersect1d(m,n)

array([3, 4, 5])

In [117]:
np.setdiff1d(n,m) # present in n but not in m

array([6, 7])

In [118]:
np.setxor1d(m,n) #present in n bot not m and then present in m but not in n

array([1, 2, 6, 7])

In [119]:
m[np.in1d(m,1)]

array([1])

### np.clip

numpy.clip() function is used to Clip (limit) the values in an array.

https://numpy.org/doc/stable/reference/generated/numpy.clip.html

In [120]:
# code
a

array([110, 530,   1,  84,  66,  91,  11,  29,  39,  64,  44,  57,  79,
        82,  80])

In [121]:
np.clip(a,a_min=25,a_max=75) #jo min ko cross karega vo min ban jaayega and jo max ko cross karega vo max ban jaayega

array([75, 75, 25, 75, 66, 75, 25, 29, 39, 64, 44, 57, 75, 75, 75])

In [122]:
# 17. np.swapaxes

In [123]:
# 18. np.uniform

In [124]:
# 19. np.count_nonzero

In [125]:
# 21. np.tile
# https://www.kaggle.com/code/abhayparashar31/best-numpy-functions-for-data-science-50?scriptVersionId=98816580

In [126]:
# 22. np.repeat
# https://towardsdatascience.com/10-numpy-functions-you-should-know-1dc4863764c5

In [127]:

# 25. np.allclose and equals